INSERT INTO tasks (name, status, priority, project_id, due_date, created_date)
VALUES ('AI Model Training', 'IN_PROGRESS', 1, 1, DATEADD(DAY, 10, CURRENT_DATE), NOW()),
       ('Data Collection', 'IN_PROGRESS', 3, 1, DATEADD(DAY, 20, CURRENT_DATE), NOW()),
       ('Algorithm Optimization', 'IN_PROGRESS', 2, 1, DATEADD(DAY, 15, CURRENT_DATE), NOW()),
       ('UI Development', 'PENDING', 3, 2, DATEADD(DAY, 20, CURRENT_DATE), NOW()),
       ('API Integration', 'IN_PROGRESS', 2, 2, DATEADD(DAY, 25, CURRENT_DATE), NOW()),
       ('Debugging', 'PENDING', 1, 2, DATEADD(DAY, 30, CURRENT_DATE), NOW()),
       ('Vulnerability Assessment', 'IN_PROGRESS', 1, 3, DATEADD(DAY, 15, CURRENT_DATE), NOW()),
       ('Firewall Configuration', 'IN_PROGRESS', 2, 3, DATEADD(DAY, 10, CURRENT_DATE), NOW()),
       ('Penetration Testing', 'PENDING', 4, 3, DATEADD(DAY, 20, CURRENT_DATE), NOW()),
       ('Painting', 'PENDING', 5, 4, DATEADD(DAY, 30, CURRENT_DATE), NOW()),
       ('Repairs', 'PENDING', 3, 4, DATEADD(DAY, 20, CURRENT_DATE), NOW()),
       ('Electrical', 'PENDING', 2, 4, DATEADD(DAY, 25, CURRENT_DATE), NOW()),
       ('Road Layout Design', 'PENDING', 1, 5, DATEADD(DAY, 25, CURRENT_DATE), NOW()),
       ('Bridge Construction Planning', 'PENDING', 3, 5, DATEADD(DAY, 35, CURRENT_DATE), NOW()),
       ('Site Inspection', 'PENDING', 2, 5, DATEADD(DAY, 20, CURRENT_DATE), NOW()),
       ('Lab Equipment Setup', 'PENDING', 4, 6, DATEADD(DAY, 35, CURRENT_DATE), NOW()),
       ('Proposal Writing', 'PENDING', 3, 6, DATEADD(DAY, 40, CURRENT_DATE), NOW()),
       ('Field Experimentation', 'PENDING', 2, 6, DATEADD(DAY, 30, CURRENT_DATE), NOW());
